// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSpTlj3IN_HVRyHBWYDqBwststrI2sCVs',
    appId: '1:902308453779:web:ea087e3b6db43228ee1c66',
    messagingSenderId: '902308453779',
    projectId: 'nutrilog-9383b',
    authDomain: 'nutrilog-9383b.firebaseapp.com',
    databaseURL: 'https://nutrilog-9383b-default-rtdb.firebaseio.com',
    storageBucket: 'nutrilog-9383b.firebasestorage.app',
    measurementId: 'G-CJFPD85RNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLe9qXQ9b3P4oAWgihTFjzJ5VmPY_Xs0',
    appId: '1:902308453779:android:0564ee22c2fab944ee1c66',
    messagingSenderId: '902308453779',
    projectId: 'nutrilog-9383b',
    databaseURL: 'https://nutrilog-9383b-default-rtdb.firebaseio.com',
    storageBucket: 'nutrilog-9383b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZLuiINSxgjQH81wgtR7q4fLHNnponBo',
    appId: '1:902308453779:ios:5fc1722e1ecdf007ee1c66',
    messagingSenderId: '902308453779',
    projectId: 'nutrilog-9383b',
    databaseURL: 'https://nutrilog-9383b-default-rtdb.firebaseio.com',
    storageBucket: 'nutrilog-9383b.firebasestorage.app',
    iosBundleId: 'com.app.nutrilog.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZLuiINSxgjQH81wgtR7q4fLHNnponBo',
    appId: '1:902308453779:ios:31d79e147463db97ee1c66',
    messagingSenderId: '902308453779',
    projectId: 'nutrilog-9383b',
    databaseURL: 'https://nutrilog-9383b-default-rtdb.firebaseio.com',
    storageBucket: 'nutrilog-9383b.firebasestorage.app',
    iosBundleId: 'com.example.nutriLog',
  );
}
