// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTA7Snv32tfZsTB_Tj08irNfjr5fjK22Y',
    appId: '1:746066998910:web:7e322ea46b37c60b4b8a2f',
    messagingSenderId: '746066998910',
    projectId: 'actionslibrary-dcfab',
    authDomain: 'actionslibrary-dcfab.firebaseapp.com',
    databaseURL: 'https://actionslibrary-dcfab.firebaseio.com',
    storageBucket: 'actionslibrary-dcfab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1XdmFwf2IhGf_-DGxYaNcJn900V66Tm0',
    appId: '1:746066998910:android:f63acc25b35355af4b8a2f',
    messagingSenderId: '746066998910',
    projectId: 'actionslibrary-dcfab',
    databaseURL: 'https://actionslibrary-dcfab.firebaseio.com',
    storageBucket: 'actionslibrary-dcfab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhAQ1cUo7pMHoXibZC865sEnkqRNr_yZA',
    appId: '1:746066998910:ios:305a3191d0e2ede04b8a2f',
    messagingSenderId: '746066998910',
    projectId: 'actionslibrary-dcfab',
    databaseURL: 'https://actionslibrary-dcfab.firebaseio.com',
    storageBucket: 'actionslibrary-dcfab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhAQ1cUo7pMHoXibZC865sEnkqRNr_yZA',
    appId: '1:746066998910:ios:305a3191d0e2ede04b8a2f',
    messagingSenderId: '746066998910',
    projectId: 'actionslibrary-dcfab',
    databaseURL: 'https://actionslibrary-dcfab.firebaseio.com',
    storageBucket: 'actionslibrary-dcfab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMLuh1fwKdQvGoJUMWZb-7Z-pFShOjkPM',
    appId: '1:746066998910:web:86282176e28a3f134b8a2f',
    messagingSenderId: '746066998910',
    projectId: 'actionslibrary-dcfab',
    authDomain: 'actionslibrary-dcfab.firebaseapp.com',
    databaseURL: 'https://actionslibrary-dcfab.firebaseio.com',
    storageBucket: 'actionslibrary-dcfab.firebasestorage.app',
  );
}
